version: 0.0
os: linux
files:
  - source: ./server/target/server.jar
    destination: /opt/server.jar
  - source: ./server/target/shaBuild
    destination: /opt/shaBuild

hooks:
  BeforeInstall:
    - location: /Scripts/calDeploysha.sh
  AfterInstall:
    - location: /Scripts/compare.sh
    - location: /Scripts/RunApp.sh
