version: 0.0
os: linux
files:
  - source: ./server/target/server.jar
    destination: /opt/
  - source: ./server/target/shaBuild
    destination: /opt/

hooks:
  BeforeInstall:
    - location: /Scripts/compare.sh
  AfterInstall: 
    - location: /Scripts/RunApp.sh
