version: 0.0
os: linux
files:
  - source: ./server.jar
    destination: /opt/server.jar
  - source: shaBuild
    destination: /opt/shaBuild
  - source: ./calDeploysha.sh
    destination: /opt/calDeploysha.sh
  - source: ./RunApp.sh
    destination: /opt/RunApp.sh
  - source: ./compare.sh
    destination: /opt/compare.sh
hooks:
  BeforeInstall:
    - location: /opt/calDeploysha.sh
  AfterInstall:
    - location: /compare.sh
    - location: /opt/compare.sh
