version: 0.0
os: linux
files:
  - source: ./target/SampleMavenTomcatApp.war
    destination: /opt/
  - source: ./target/shaBuild
    destination: /opt/
hooks:
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
  BeforeInstall:
    - location: scripts/compare.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_application
      timeout: 300
  ValidateService:
    - location: scripts/basic_health_check.sh

