version: 0.1

phases:

  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
      - sha1sum  target/SampleMavenTomcatApp.war |  awk '{ print $1 }' > target/shaBuild
      - sha1sum  target/SampleMavenTomcatApp.war |  awk '{ print $1 }'

artifacts:
  files:
    - '**/*'
