#!/bin/bash

set -e

# CATALINA_HOME='/usr/share/tomcat/'

# cp /opt/SampleMavenTomcatApp.war $CATALINA_HOME/webapps/

# chown tomcat:tomcat -R /usr/share/tomcat/

# $CATALINA_HOME/bin/catalina.sh start

docker kill $(docker ps -q)

cd /opt/

docker build -t hello  .

docker run -itd -p 80:8080 hello